apply plugin: 'com.android.application'

android {
    namespace 'com.vivian.glass'
    compileSdk 34

    defaultConfig {
        applicationId "com.vivian.glass"
        minSdkVersion 19
        targetSdkVersion 19
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    lint {
        abortOnError false
    }
}

dependencies {
    implementation 'org.java-websocket:Java-WebSocket:1.5.3'
    compileOnly files('libs/gdk.jar')
}
